### PR TITLE
Added beginning framework for unit tests & code coverage

### PR DESCRIPTION
**Pull request by kayila**
Just putting the infrastructure in place to work on adding more unit tests.

### CODE REVIEW

**Review by JamzTheMan — APPROVED** [review]
Looks good. I assume you want to keep this on it's own branch until it's all done and ready to merge into the next-release branch?

**Comment by JamzTheMan** [comment]
ug, I didn't want to put this into master yet, my bad. :(
dang.

**Comment by kayila** [comment]
Thats ok! This won't cause any problems in master, and it frees things up
so we can write unit tests and slowly get them into master.

**Comment by kayila** [comment]
But yes, I would like to keep the testing branch around for the time being.

**Comment by JamzTheMan** [comment]
Yea, I normally want to keep the master branch == to what is in production. If there is a production issue, you can pull master branch and run the same code and test.

I'll leave this as is for now vs creating another PR to undo the PR since there isn't any "code" changes and the gradle doesn't change any dependencies and such.

Going forward, lets submit all PR's to the next-release branch. (or other feature branches as needed)

**Comment by JamzTheMan** [comment]
FYI: I'm following the simple workflow: https://guides.github.com/introduction/flow/

(posting in general and for others that may come across this discussion)

**Comment by kayila** [comment]
Should probably merge master into next-release then... Or at least
cherrypick the commit

**Comment by JamzTheMan** [comment]
true, will do.

**Pull request merged**
