### PR TITLE
Token drift

### PR DESCRIPTION
**Pull request by kayila**

### CODE REVIEW

**Review by JamzTheMan — APPROVED** [review]
Looks good! I'll merge it in and test it manually.

**Comment by JamzTheMan** [comment]
FYI: I keep reading this as Tokyo Drift.... :)

**Comment by JamzTheMan** [comment]
@kayila Do we have this tracked in RPTools/maptool? I'm trying to move what we need from this fork back to RPTools.

**Comment by kayila** [comment]
Not as far as I know.

**Comment by JamzTheMan** [comment]
I believe what you had finished here and merged is now in RPTools. Can you verify that?

So what is left, IIRC is phase 2 as this merge still didn't fix all if this.

Is this related to what Jagged is working on for hex drag?

**Comment by kayila** [comment]
I can confirm that this is **not** in rptools. I believe since it didn't fix the full problem, you rolled it back. We should open a new issue in the rptools repo and handle it in there. I believe Jagged's work may fix this, so I'd like to wait for them to finish before taking another look at this issue.

**Comment by JamzTheMan** [comment]
Ok, no problem.

**Pull request merged**
